---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: w2012r2-upd
    transport:
      name: winrm

suites:
  - name: default
    run_list:
      - recipe[Task5::default]
    attributes:
