---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows-2012
    transport:
      name: winrm
    driver:
      guest: :windows
      box: w2012r2-upd
      winrm:
        username: vagrant
        password: vagrant
      gui: true

suites:
  - name: default
    run_list:
      - recipe[Task5::default]
    attributes:
