name             'Task5'
maintainer       'Dmytro'
maintainer_email 'dfad1ripe@gmail.com'
license          'none'
description      'W2012 + GreenShot'
long_description 'Installs/Configures Greenshot, Powershell etc.'
version          '0.0.1'
issues_url       'http://bash.im/'
source_url       'https://github.com/dfad1ripe/df_devops_task5'
